export { default as Footer } from './Footer/Footer'
export * from './Footer/Footer'
export { default as NewsletterSection } from './NewsletterSection/NewsletterSection'
export { default as Page } from './Page/Page'
export { default as ErrorPage } from './ErrorPage/ErrorPage'
export { default as PageBrand } from './PageBrand/PageBrand'
