export { default as Footer } from './Footer/Footer'
export { default as ChangePasswordForm } from './ChangePasswordForm/ChangePasswordForm'
export { default as Page } from './Page/Page'
export { default as SignUpForm } from './SignUpForm/SignUpForm'
export { default as LoginForm } from './LoginForm/LoginForm'
