name: e2e-tests-action
on:
  push:
    branches:
      - develop # todo: remove
  pull_request:
    branches:
      - develop # todo: replace with master
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Tests
        uses: cypress-io/github-action@v2
