name: e2e-tests-action
on:
  push: # todo: replace with pull_request
    branches:
      - develop # todo: replace with master
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/e2e
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn add cypress@6.8.0
      - name: Run Tests
        run: yarn start
