name: e2e-tests-action
on:
  push:
    branches:
      - develop # todo master
  pull_request:
    branches:
      - develop # todo master
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
